export const DASHBOARD_REDUX_CONSTANTS = {
  DASHBOARD_DETAILS: 'DASHBOARD_DETAILS',
  DASHBOARD_USER_LIST_DETAILS: 'DASHBOARD_USER_LIST_DETAILS',
  RESET_DASHBOARD_DETAILS: 'RESET_DASHBOARD_DETAILS',
};
