export const APPLICATION_REDUX_CONSTANTS = {
  APPLICATION_LIST: 'APPLICATION_LIST',
};
export const APPLICATION_COLUMN_LIST_REDUX_CONSTANTS = {
  APPLICATION_COLUMN_LIST_ACTION: 'APPLICATION_COLUMN_LIST_ACTION',
  UPDATE_APPLICATION_COLUMN_LIST_ACTION: 'UPDATE_APPLICATION_COLUMN_LIST_ACTION',
};
