export const MY_WORK_REDUX_CONSTANTS = {
  MY_WORK_TASK_REDUX_CONSTANTS: {
    TASK_LIST_ACTION: 'TASK_LIST_ACTION',
    TASK_COLUMN_NAME_LIST_ACTION: 'TASK_COLUMN_NAME_LIST_ACTION',
    UPDATE_TASK_COLUMN_NAME_LIST_ACTION: 'UPDATE_TASK_COLUMN_NAME_LIST_ACTION',
    ASSIGNEE_DROP_DOWN_DATA_FOR_FILTER: 'ASSIGNEE_DROP_DOWN_DATA_FOR_FILTER',
    RESET_PAGE_DATA: 'RESET_PAGE_DATA',

    // ADD new task
    UPDATE_ADD_TASK_FIELD_ACTION: 'UPDATE_ADD_TASK_FIELD_ACTION',
    ASSIGNEE_DROP_DOWN_DATA_ACTION: 'ASSIGNEE_DROP_DOWN_DATA_ACTION',
    ENTITY_DROP_DOWN_DATA_ACTION: 'ENTITY_DROP_DOWN_DATA_ACTION',
    RESET_ADD_TASK_STATE_ACTION: 'RESET_ADD_TASK_STATE_ACTION',

    // EDIT task
    GET_TASK_DETAIL_BY_ID_ACTION: 'GET_TASK_DETAIL_BY_ID_ACTION',
    UPDATE_EDIT_TASK_FIELD_ACTION: 'UPDATE_EDIT_TASK_FIELD_ACTION',
    RESET_EDIT_TASK_STATE_ACTION: 'RESET_EDIT_TASK_STATE_ACTION',
    ENTITY_DROP_DOWN_DATA_FOR_UPDATE_ACTION: 'ENTITY_DROP_DOWN_DATA_FOR_ACTION_ACTION',
  },
};
