export const USER_MANAGEMENT_REDUX_CONSTANTS = {
  USER_MANAGEMENT_LIST_USER_ACTION: 'USER_MANAGEMENT_LIST_USER_ACTION',
};

export const USER_MANAGEMENT_COLUMN_LIST_REDUX_CONSTANTS = {
  USER_MANAGEMENT_COLUMN_LIST_ACTION: 'USER_MANAGEMENT_COLUMN_LIST_ACTION',
  UPDATE_USER_MANAGEMENT_COLUMN_LIST_ACTION: 'UPDATE_USER_MANAGEMENT_COLUMN_LIST_ACTION',
};
