export const SETTING_REDUX_CONSTANTS = {
  DOCUMENT_TYPE: {
    FETCH_DOCUMENT_TYPE_LIST_REQUEST: 'FETCH_DOCUMENT_TYPE_LIST_REQUEST',
    FETCH_DOCUMENT_TYPE_LIST_SUCCESS: 'FETCH_DOCUMENT_TYPE_LIST_SUCCESS',
    FETCH_DOCUMENT_TYPE_LIST_FAILURE: 'FETCH_DOCUMENT_TYPE_LIST_FAILURE',
    RESET_PAGE_DATA: 'RESET_PAGE_DATA',

    ADD_DOCUMENT_TYPE: {
      UPDATE_DOCUMENT_TYPE_FIELDS: 'UPDATE_DOCUMENT_TYPE_FIELDS',
      RESET_ADD_DOC_TYPE_DATA: 'RESET_ADD_DOC_TYPE_DATA',
    },
    EDIT_DOCUMENT_TYPE: {
      GET_DOCTYPE_DETAIL: 'GET_DOCTYPE_DETAIL',
      UPDATE_DOCUMENT_TYPE_FIELDS: 'UPDATE_DOCUMENT_TYPE_FIELDS',
      RESET_ADD_DOC_TYPE_DATA: 'RESET_ADD_DOC_TYPE_DATA',
    },
  },
};
