export const SETTING_REDUX_CONSTANTS = {
  DOCUMENT_TYPE: {
    FETCH_DOCUMENT_TYPE_LIST_REQUEST: 'FETCH_DOCUMENT_TYPE_LIST_REQUEST',
    FETCH_DOCUMENT_TYPE_LIST_SUCCESS: 'FETCH_DOCUMENT_TYPE_LIST_SUCCESS',
    FETCH_DOCUMENT_TYPE_LIST_FAILURE: 'FETCH_DOCUMENT_TYPE_LIST_FAILURE',
    RESET_PAGE_DATA: 'RESET_PAGE_DATA',

    ADD_DOCUMENT_TYPE: {
      UPDATE_DOCUMENT_TYPE_FIELDS: 'UPDATE_DOCUMENT_TYPE_FIELDS',
      RESET_ADD_DOC_TYPE_DATA: 'RESET_ADD_DOC_TYPE_DATA',
    },
    EDIT_DOCUMENT_TYPE: {
      GET_DOCTYPE_DETAIL: 'GET_DOCTYPE_DETAIL',
      UPDATE_DOCUMENT_TYPE_FIELDS: 'UPDATE_DOCUMENT_TYPE_FIELDS',
      RESET_ADD_DOC_TYPE_DATA: 'RESET_ADD_DOC_TYPE_DATA',
    },
  },
  ORGANIZATION_DETAILS: {
    FETCH_ORGANIZATION_DETAILS_SUCCESS: 'FETCH_ORGANIZATION_DETAILS_SUCCESS',
    FETCH_ORGANIZATION_DETAILS_FAILURE: 'FETCH_ORGANIZATION_DETAILS_FAILURE',
  },
  API_INTEGRATION: {
    FETCH_API_INTEGRATION_SUCCESS: 'FETCH_API_INTEGRATION_SUCCESS',
    FETCH_API_INTEGRATION_FAILURE: 'FETCH_API_INTEGRATION_FAILURE',
  },
  AUDIT_LOG: {
    FETCH_AUDIT_LOG_LIST_SUCCESS: 'FETCH_AUDIT_LOG_LIST_SUCCESS',
  },
};
