export const SIDEBAR_URLS = [
  {
    label: 'Dashboard',
    title: 'Dashboard',
    icon: 'assessment',
    url: '/dashboard',
    name: 'dashboard',
  },
  {
    label: 'My Work',
    title: 'My Work',
    icon: 'event_available',
    url: '/my-work',
    name: 'my-work',
  },
  {
    label: 'Application',
    title: 'Application',
    icon: 'business_center',
    url: '/application',
    name: 'application',
  },
  {
    label: 'Clients',
    title: 'Clients',
    icon: 'supervisor_account',
    url: '/clients',
    name: 'client',
  },
  {
    label: 'Debtors',
    title: 'Debtor Management',
    icon: 'account_circle',
    url: '/debtors',
    name: 'debtor',
  },
  {
    label: 'Claims',
    title: 'Claims',
    icon: 'class',
    url: '/claims',
    name: 'claim',
  },
  {
    label: 'Overdues',
    title: 'Overdues',
    icon: 'list_alt',
    url: '/over-dues',
    name: 'overdue',
  },
  {
    label: 'Insurer',
    title: 'Insurer',
    icon: 'text_snippet',
    url: '/insurer',
    name: 'insurer',
  },
  {
    label: 'Users',
    title: 'User Management',
    icon: 'admin_panel_settings',
    url: '/users',
    name: 'user',
  },
  {
    label: 'Reports',
    title: 'Reports',
    icon: 'pie_chart',
    url: '/reports',
    name: 'report',
  },
  {
    label: 'Settings',
    title: 'Settings',
    icon: 'settings',
    url: '/settings',
    name: 'settings',
  },
];
