export const INSURER_REDUX_CONSTANTS = {
  INSURER_LIST_USER_ACTION: 'INSURER_LIST_USER_ACTION',
};

export const INSURER_CRM_REDUX_CONSTANTS = {
  INSURER_GET_LIST_FROM_CRM_ACTION: 'INSURER_GET_LIST_FROM_CRM_ACTION',
  INSURER_GET_SEARCH_LIST_FROM_CRM_ACTION: 'INSURER_GET_SEARCH_LIST_FROM_CRM_ACTION',
};

export const INSURER_COLUMN_LIST_REDUX_CONSTANTS = {
  INSURER_COLUMN_LIST_ACTION: 'INSURER_COLUMN_LIST_ACTION',
  UPDATE_INSURER_COLUMN_LIST_ACTION: 'UPDATE_INSURER_COLUMN_LIST_ACTION',
};
export const INSURER_VIEW_REDUX_CONSTANT = {
  VIEW_INSURER_DATA: 'VIEW_INSURER_DATA',
  CONTACT: {
    INSURER_CONTACT_LIST_USER_ACTION: 'INSURER_CONTACT_LIST_USER_ACTION',
    INSURER_CONTACT_COLUMN_LIST_ACTION: 'INSURER_CONTACT_COLUMN_LIST_ACTION',
    UPDATE_INSURER_CONTACT_COLUMN_LIST_ACTION: 'UPDATE_INSURER_CONTACT_COLUMN_LIST_ACTION',
  },
  POLICIES: {
    INSURER_POLICIES_LIST_USER_ACTION: 'INSURER_POLICIES_LIST_USER_ACTION',
    INSURER_POLICIES_COLUMN_LIST_ACTION: 'INSURER_POLICIES_COLUMN_LIST_ACTION',
    UPDATE_POLICIES_CONTACT_COLUMN_LIST_ACTION: 'UPDATE_POLICIES_CONTACT_COLUMN_LIST_ACTION',
  },
};
