export const EDIT_PROFILE_CONSTANT = {
  GET_LOGGED_USER_DETAILS: 'GET_LOGGED_USER_DETAILS',
  USER_EDIT_PROFILE_DATA_CHANGE: 'USER_EDIT_PROFILE_DATA_CHANGE',
};
export const USER_PROFILE_PICTURE_CONSTANT = {
  UPLOAD_USER_PROFILE_PICTURE: 'UPLOAD_USER_PROFILE_PICTURE',
};
