export const REPORTS_REDUX_CONSTANTS = {
  GET_REPORT_LIST_REQUEST: 'GET_REPORT_LIST_REQUEST',
  GET_REPORT_LIST_SUCCESS: 'GET_REPORT_LIST_SUCCESS',
  GET_REPORT_LIST_FAILURE: 'GET_REPORT_LIST_FAILURE',

  GET_REPORT_COLUMN_LIST: 'GET_REPORT_COLUMN_LIST',
  GET_REPORT_DEFAULT_COLUMN_LIST: 'GET_REPORT_DEFAULT_COLUMN_LIST',
  UPDATE_REPORT_COLUMN_LIST: 'UPDATE_REPORT_COLUMN_LIST',

  GET_DROPDOWN_CLIENT_LIST: 'GET_DROPDOWN_CLIENT_LIST',

  UPDATE_REPORT_FILTER_FIELDS: 'UPDATE_REPORT_FILTER_FIELDS',

  RESET_REPORT_FILTER: 'RESET_REPORT_FILTER',
};
