export const DEBTORS_REDUX_CONSTANTS = {
  DEBTORS_LIST_USER_ACTION: 'DEBTORS_LIST_USER_ACTION',
  SELECTED_DEBTORS_DATA: 'SELECTED_DEBTORS_DATA',
  DEBTOR_LIST_RESET_PAGE_DATA: 'DEBTOR_LIST_RESET_PAGE_DATA',

  NOTES: {
    DEBTORS_NOTES_LIST_USER_ACTION: 'DEBTORS_NOTES_LIST_USER_ACTION',
  },
  DOCUMENTS: {
    DEBTOR_DOCUMENTS_LIST_USER_ACTION: 'DEBTOR_DOCUMENTS_LIST_USER_ACTION',
    DEBTOR_DOCUMENTS_MANAGEMENT_COLUMN_LIST_ACTION:
      'DEBTOR_DOCUMENTS_MANAGEMENT_COLUMN_LIST_ACTION',
    UPDATE_DEBTOR_DOCUMENTS_COLUMN_LIST_ACTION: 'UPDATE_DEBTOR_DOCUMENTS_COLUMN_LIST_ACTION',
    DEBTOR_DOCUMENT_TYPE_LIST_USER_ACTION: 'DEBTOR_DOCUMENT_TYPE_LIST_USER_ACTION',
    UPLOAD_DOCUMENT_DEBTOR_ACTION: 'UPLOAD_DOCUMENT_DEBTOR_ACTION',
  },
  TASK: {
    DEBTOR_TASK_LIST_ACTION: 'DEBTOR_TASK_LIST_ACTION',
    DEBTOR_TASK_COLUMN_NAME_LIST_ACTION: 'DEBTOR_TASK_COLUMN_NAME_LIST_ACTION',
    UPDATE_DEBTOR_TASK_COLUMN_NAME_LIST_ACTION: 'UPDATE_DEBTOR_TASK_COLUMN_NAME_LIST_ACTION',
    ADD_TASK: {
      UPDATE_ADD_TASK_FIELD_ACTION: 'UPDATE_ADD_TASK_FIELD_ACTION',
      ASSIGNEE_DROP_DOWN_DATA_ACTION: 'ASSIGNEE_DROP_DOWN_DATA_ACTION',
      ENTITY_DROP_DOWN_DATA_ACTION: 'ENTITY_DROP_DOWN_DATA_ACTION',
      DEFAULT_ENTITY_DROP_DOWN_DATA_ACTION: 'DEFAULT_ENTITY_DROP_DOWN_DATA_ACTION',
      RESET_ADD_TASK_STATE_ACTION: 'RESET_ADD_TASK_STATE_ACTION',
    },
    EDIT_TASK: {
      GET_DEBTOR_TASK_DETAILS_ACTION: 'GET_DEBTOR_TASK_DETAILS_ACTION',
    },
  },
  APPLICATION: {
    DEBTOR_APPLICATION_LIST_ACTION: 'DEBTOR_APPLICATION_LIST_ACTION',
    DEBTOR_APPLICATION_COLUMN_LIST_ACTION: 'DEBTOR_APPLICATION_COLUMN_LIST_ACTION',
    UPDATE_DEBTOR_APPLICATION_COLUMN_LIST_ACTION: 'UPDATE_DEBTOR_APPLICATION_COLUMN_LIST_ACTION',
  },

  CREDIT_LIMIT: {
    DEBTOR_CREDIT_LIMIT_LIST_ACTION: 'DEBTOR_CREDIT_LIMIT_LIST_ACTION',
    DEBTOR_CREDIT_LIMIT_COLUMN_LIST_ACTION: 'DEBTOR_CREDIT_LIMIT_COLUMN_LIST_ACTION',
    UPDATE_DEBTOR_CREDIT_LIMIT_COLUMN_LIST_ACTION: 'UPDATE_DEBTOR_CREDIT_LIMIT_COLUMN_LIST_ACTION',
  },

  STAKE_HOLDER: {
    DEBTOR_STAKE_HOLDER_LIST_ACTION: 'DEBTOR_STAKE_HOLDER_LIST_ACTION',
    DEBTOR_STAKE_HOLDER_COLUMN_LIST_ACTION: 'DEBTOR_STAKE_HOLDER_COLUMN_LIST_ACTION',
    UPDATE_DEBTOR_STAKE_HOLDER_COLUMN_LIST_ACTION: 'UPDATE_DEBTOR_STAKE_HOLDER_COLUMN_LIST_ACTION',
  },
};
export const DEBTORS_MANAGEMENT_COLUMN_LIST_REDUX_CONSTANTS = {
  DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION: 'DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION',
  UPDATE_DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION: 'UPDATE_DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION',
};
export const DEBTOR_MANAGEMENT_CRUD_REDUX_CONSTANTS = {
  DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ACTION: 'DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ACTION',
  DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ADDRESS_ACTION: 'DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ADDRESS_ACTION',
  DEBTORS_MANAGEMENT_DROPDOWN_LIST_REDUX_CONSTANTS:
    'DEBTORS_MANAGEMENT_DROPDOWN_LIST_REDUX_CONSTANTS',
};
