export const DEBTORS_REDUX_CONSTANTS = {
  DEBTORS_LIST_USER_ACTION: 'DEBTORS_LIST_USER_ACTION',
  SELECTED_DEBTORS_DATA: 'SELECTED_DEBTORS_DATA',

  NOTES: {
    DEBTORS_NOTES_LIST_USER_ACTION: 'DEBTORS_NOTES_LIST_USER_ACTION',
  },
};
export const DEBTORS_MANAGEMENT_COLUMN_LIST_REDUX_CONSTANTS = {
  DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION: 'DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION',
  UPDATE_DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION: 'UPDATE_DEBTORS_MANAGEMENT_COLUMN_LIST_ACTION',
};
export const DEBTOR_MANAGEMENT_CRUD_REDUX_CONSTANTS = {
  DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ACTION: 'DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ACTION',
  DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ADDRESS_ACTION: 'DEBTOR_MANAGEMENT_UPDATE_DEBTOR_ADDRESS_ACTION',
  DEBTORS_MANAGEMENT_DROPDOWN_LIST_REDUX_CONSTANTS: 'DEBTORS_MANAGEMENT_DROPDOWN_LIST_REDUX_CONSTANTS',
};
