export const CLIENT_REDUX_CONSTANTS = {
  CLIENT_LIST_USER_ACTION: 'CLIENT_LIST_USER_ACTION',
  SELECTED_CLIENT_DATA: 'SELECTED_CLIENT_DATA',

  CREDIT_LIMIT: {
    CLIENT_CREDIT_LIMIT_LIST_ACTION: 'CLIENT_CREDIT_LIMIT_LIST_ACTION',
    CLIENT_CREDIT_LIMIT_COLUMN_LIST_ACTION: 'CLIENT_CREDIT_LIMIT_COLUMN_LIST_ACTION',
    UPDATE_CLIENT_CREDIT_LIMIT_COLUMN_LIST_ACTION: 'UPDATE_CLIENT_CREDIT_LIMIT_COLUMN_LIST_ACTION',
  },

  APPLICATION: {
    CLIENT_APPLICATION_LIST_ACTION: 'CLIENT_APPLICATION_LIST_ACTION',
    CLIENT_APPLICATION_COLUMN_LIST_ACTION: 'CLIENT_APPLICATION_COLUMN_LIST_ACTION',
    UPDATE_CLIENT_APPLICATION_COLUMN_LIST_ACTION: 'UPDATE_CLIENT_APPLICATION_COLUMN_LIST_ACTION',
  },

  CONTACT: {
    CLIENT_CONTACT_LIST_USER_ACTION: 'CLIENT_CONTACT_LIST_USER_ACTION',
    CLIENT_CONTACT_COLUMN_LIST_USER_ACTION: 'CLIENT_CONTACT_COLUMN_LIST_USER_ACTION',
    UPDATE_CLIENT_CONTACT_COLUMN_LIST_ACTION: 'UPDATE_CLIENT_CONTACT_COLUMN_LIST_ACTION',
  },

  POLICIES: {
    CLIENT_POLICIES_LIST_USER_ACTION: 'CLIENT_POLICIES_LIST_USER_ACTION',
    CLIENT_POLICIES_COLUMN_LIST_USER_ACTION: 'CLIENT_POLICIES_COLUMN_LIST_USER_ACTION',
    UPDATE_CLIENT_POLICIES_COLUMN_LIST_ACTION: 'UPDATE_CLIENT_POLICIES_COLUMN_LIST_ACTION',
  },

  NOTES: {
    CLIENT_NOTES_LIST_USER_ACTION: 'CLIENT_NOTES_LIST_USER_ACTION',
  },
  DOCUMENTS: {
    CLIENT_DOCUMENTS_LIST_USER_ACTION: 'CLIENT_DOCUMENTS_LIST_USER_ACTION',
    CLIENT_DOCUMENTS_MANAGEMENT_COLUMN_LIST_ACTION:
      'CLIENT_DOCUMENTS_MANAGEMENT_COLUMN_LIST_ACTION',
    UPDATE_CLIENT_DOCUMENTS_COLUMN_LIST_ACTION: 'UPDATE_CLIENT_DOCUMENTS_COLUMN_LIST_ACTION',
    CLIENT_DOCUMENT_TYPE_LIST_USER_ACTION: 'CLIENT_DOCUMENT_TYPE_LIST_USER_ACTION',
    UPLOAD_DOCUMENT_CLIENT_ACTION: 'UPLOAD_DOCUMENT_CLIENT_ACTION',
  },
};
export const CLIENT_MANAGEMENT_COLUMN_LIST_REDUX_CONSTANTS = {
  CLIENT_MANAGEMENT_COLUMN_LIST_ACTION: 'CLIENT_MANAGEMENT_COLUMN_LIST_ACTION',
  UPDATE_CLIENT_MANAGEMENT_COLUMN_LIST_ACTION: 'UPDATE_CLIENT_MANAGEMENT_COLUMN_LIST_ACTION',
};
export const CLIENT_MANAGEMENT_FILTER_LIST_REDUX_CONSTANTS = {
  CLIENT_MANAGEMENT_FILTER_LIST_ACTION: 'CLIENT_MANAGEMENT_FILTER_LIST_ACTION',
};
export const CLIENT_ADD_FROM_CRM_REDUX_CONSTANT = {
  CLIENT_GET_LIST_FROM_CRM_ACTION: 'CLIENT_GET_LIST_FROM_CRM_ACTION',
  CLIENT_SEARCH_LIST_IN_CRM_ACTION: 'CLIENT_SEARCH_LIST_IN_CRM_ACTION',
};
