export const CLIENT_REDUX_CONSTANTS = {
  CLIENT_LIST_USER_ACTION: 'CLIENT_LIST_USER_ACTION',
  SELECTED_CLIENT_DATA: 'SELECTED_CLIENT_DATA',
  CONTACT: {
    CLIENT_CONTACT_LIST_USER_ACTION: 'CLIENT_CONTACT_LIST_USER_ACTION',
    CLIENT_CONTACT_COLUMN_LIST_USER_ACTION: 'CLIENT_CONTACT_COLUMN_LIST_USER_ACTION',
  },
};
